name: docker-build

on:
  schedule:
    - cron: "0 10 * * *"
  push:
    branches-ignore:
      - main
    tags:
      - "v*.*.*"
  pull_request:

jobs:
  docker:
    uses: geokrety/geokrety-gha-workflows/.github/workflows/docker-build.yml@main
    with:
      image_name: geokrety/nginx
      dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
      dockerfile: Dockerfile
    secrets:
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  update-version-set:
    uses: geokrety/geokrety-gha-workflows/.github/workflows/version-set.yml@main
    needs: docker
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  deploy:
    needs: docker
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: geokrety/geokrety-gha-workflows/.github/actions/docker-build@main
        with:
          header_name: ${{ secrets.DEPLOY_HEADER_NAME }}
          header_value: ${{ secrets.DEPLOY_HEADER_VALUE }}
          webhook_endpoint: ${{ secrets.DEPLOY_URL }}
