
name: Automatic release

on:
  push:
    branches:
      - main

jobs:
  pre-commit:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: geokrety/geokrety-gha-workflows/.github/actions/pre-commit.yml@main

  docker:
    needs: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: geokrety/geokrety-gha-workflows/.github/actions/docker-build.yml@main
        with:
          image_name: geokrety/nginx
          dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  semantic-release:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - uses: geokrety/geokrety-gha-workflows/.github/actions/semantic-release.yml@main
        with:
          token: ${{ secrets.GH_TOKEN }}
